### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by Plib0296** [derekhe/msfs2020-google-map#105]
BEFORE SUBMIT A BUG, PLEASE READ THE FAQ PAGE HERE: https://github.com/derekhe/msfs2020-google-map/wiki/FAQ

**Describe the bug**
"Use embedded python"
Restoring hosts
Restoring hosts
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\steve\Desktop\Games Shortcuts\Google Maps Mod\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\steve\Desktop\Games Shortcuts\Google Maps Mod\src\app.py", line 254, in run
    self.stop()
  File "C:\Users\steve\Desktop\Games Shortcuts\Google Maps Mod\src\app.py", line 337, in stop
    restore_hosts()
  File "C:\Users\steve\Desktop\Games Shortcuts\Google Maps Mod\src\runner.py", line 53, in restore_hosts
    with open(host_path, "r+") as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Windows\\System32\\drivers\\etc\\hosts'

**To Reproduce**
Clicked 'Run' in the Google Maps Dialog

**Screenshots**

**Desktop (please complete the following information):**
 - MOD Version [e.g. 22]
 - MSFS Version, MS Store or Stream

**Additional context**

**Comment by derekhe** [comment]
https://github.com/derekhe/msfs2020-google-map/wiki/FAQ#host-related-issue

**Comment by derekhe** [comment]
@Plib0296 
Did you fix it?

**Comment by GrimReaper7993** [comment]
Help, did not copy original Bing maps file. Trying to delete the two lines of code but can't. Also, not able to restore to first version. Need to change back from the google maps mod to bing so that i can play online. pls help.

**Comment by derekhe** [comment]
It normally caused by antivirus which locks your hosts file.
Please have a look at : https://github.com/derekhe/msfs2020-google-map/wiki/FAQ#antivirus

**Comment by derekhe** [comment]
@Plib0296 fixed?

**Comment by MAX767300ER** [comment]
Hi! thanks for your valuable time! I am encountering the above issue, tried to delete the host file but the program does not create a new one and after running run.but i get the below message.
C:\Users\massi\OneDrive\Desktop\mod maps>if exist .\Python39\python.exe (
echo "Use embedded python"
 .\Python39\python.exe src\app.py
)  else (
echo "Use user python"
 py -m pip install -r requirements.txt
 py src\app.py
)
"Use embedded python"
Restoring hosts
Restoring hosts
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\massi\OneDrive\Desktop\mod maps\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\massi\OneDrive\Desktop\mod maps\src\app.py", line 254, in run
    self.stop()
  File "C:\Users\massi\OneDrive\Desktop\mod maps\src\app.py", line 337, in stop
    restore_hosts()
  File "C:\Users\massi\OneDrive\Desktop\mod maps\src\runner.py", line 52, in restore_hosts
    os.chmod(host_path, stat.S_IWRITE)
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato: 'C:\\Windows\\System32\\drivers\\etc\\hosts'


Many thanks for your help

**Comment by GrimReaper7993** [comment]
Not sure yet. Away from computer for a bit.

Sent via the Samsung Galaxy S10, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by derekhe** [comment]
@MAX767300ER  you can create a new empty hosts file using notepad using adminitrator mode.

**Comment by MAX767300ER** [comment]
It's working perfectly now! Many thanks for your support! Max
