### ISSUE TITLE
[BUG] UnicodeDecodeError?

### ISSUE THREAD

**Issue by seiermax** [derekhe/msfs2020-google-map#150]
Installed the program under latest updated versions of MSFS store edition and Windows

**Comment by seiermax** [comment]
When I start the bat, it immediately stops again. The contents of the text window is:

E:\Hilfsprogramme\Google Maps Replacement\msfs2020-google-map-2021-12-04_3ULI0>.\Python39\python.exe src\app.py
Restoring hosts
Restoring hosts
Exception in Tkinter callback
Traceback (most recent call last):
  File "E:\Hilfsprogramme\Google Maps Replacement\msfs2020-google-map-2021-12-04_3ULI0\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "E:\Hilfsprogramme\Google Maps Replacement\msfs2020-google-map-2021-12-04_3ULI0\src\app.py", line 241, in run
    self.stop()
  File "E:\Hilfsprogramme\Google Maps Replacement\msfs2020-google-map-2021-12-04_3ULI0\src\app.py", line 313, in stop
    restore_hosts()
  File "E:\Hilfsprogramme\Google Maps Replacement\msfs2020-google-map-2021-12-04_3ULI0\src\runner.py", line 36, in restore_hosts
    host = f.read()
  File "E:\Hilfsprogramme\Google Maps Replacement\msfs2020-google-map-2021-12-04_3ULI0\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
_UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 454804: character maps to <undefined>_

Any idea about what I did wrong and how to fix the problem?
TY all in advance for your support
