### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by SergioBopp** [derekhe/msfs2020-google-map#167]
Hi
I'm getting this error message:

**C:\MSFS2020-Google-Map>.\Python39\python.exe src\app.py
Restoring hosts
Restoring hosts
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\MSFS2020-Google-Map\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\MSFS2020-Google-Map\src\app.py", line 241, in run
    self.stop()
  File "C:\MSFS2020-Google-Map\src\app.py", line 313, in stop
    restore_hosts()
  File "C:\MSFS2020-Google-Map\src\runner.py", line 35, in restore_hosts
    with open(host_path, "r+") as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Windows\\System32\\drivers\\etc\\hosts'**

Is there any way to resolve this ?

**Comment by derekhe** [comment]
Please refer to: https://github.com/derekhe/msfs2020-google-map/wiki/FAQ
