### ISSUE TITLE
软路由科学上网如何设置？留空或者修改软路由的地址，都无法启动server~

### ISSUE THREAD

**Issue by cokar** [derekhe/msfs2020-google-map#2]
无法启动！显示如下信息

`root "受信任的根证书颁发机构"
相关证书:

精确匹配:
元素 8:
序列号: 1e35e0ede2501f81dafdd462b1632ef6
颁发者: CN=mkcert DESKTOP-O2CB4QF\derekhe@DESKTOP-O2CB4QF, OU=DESKTOP-O2CB4QF\derekhe@DESKTOP-O2CB4QF, O=mkcert development CA
 NotBefore: 2021/8/15 0:17
 NotAfter: 2023/11/15 0:17
使用者: OU=DESKTOP-O2CB4QF\derekhe@DESKTOP-O2CB4QF, O=mkcert development certificate
非根证书
证书哈希(sha1): 962050be3c49c3aff75f025a676cf3b202245a83

证书 "DESKTOP-O2CB4QF\derekhe@DESKTOP-O2CB4QF" 已经在存储中。
CertUtil: -addstore 命令成功完成。
Proxy url
 * Serving Flask app 'server' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "server.py", line 92, in <module>
  File "flask\app.py", line 922, in run
  File "werkzeug\serving.py", line 1008, in run_simple
  File "werkzeug\serving.py", line 948, in inner
  File "werkzeug\serving.py", line 780, in make_server
  File "werkzeug\serving.py", line 686, in __init__
  File "socketserver.py", line 452, in __init__
  File "http\server.py", line 138, in server_bind
  File "socketserver.py", line 466, in server_bind
OSError: [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。
[6784] Failed to execute script 'server' due to unhandled exception!`

**Comment by derekhe** [comment]
这个可能是因为你的本地的443端口被占用了导致，你可以尝试找一下哪个应用占用了443。
另外记得用管理员权限启动应用

**Comment by cokar** [comment]
> 这个可能是因为你的本地的443端口被占用了导致，你可以尝试找一下哪个应用占用了443。
> 另外记得用管理员权限启动应用

确实是用管理员权限启动的！
另外，我用软路由作为网关科学上网，那么config.ini文件中是不是填写软路由网关地址？

**Comment by derekhe** [comment]
如果可以直接访问谷歌，可以把url = 后面置空试试
另外有些软路由提供了http端口的，可以用软路由的http代理端口

**Comment by cokar** [comment]
> 如果可以直接访问谷歌，可以把url = 后面置空试试
> 另外有些软路由提供了http端口的，可以用软路由的http代理端口

我按照你说的，url = 后面留空；因为我的软路由是PAC自动判断国内外的IP所以无需做更多端口设置
然后我更新了1.1.0版本，进入游戏之后，发现它工作得很顺畅！
非常感谢！这个工具真是太完美了

**Comment by derekhe** [comment]
不错不错！谢谢，帮我推广推广哈，我就关贴了。
