### ISSUE TITLE
出現了這個怎麼辦

### ISSUE THREAD

**Issue by Dfaker-HK** [derekhe/msfs2020-google-map#37]
C:\Users\choyt\Downloads\msfs2020-google-map-2021-09-28>if exist .\Python39\python.exe (
echo "Use embedded python"
 .\Python39\python.exe src\app.py
)  else (
echo "Use user python"
 py -m pip install -r requirements.txt
 py src\app.py
)
"Use embedded python"
Traceback (most recent call last):
  File "C:\Users\choyt\Downloads\msfs2020-google-map-2021-09-28\src\app.py", line 11, in <module>
    from runner import add_cert, override_hosts, restore_hosts
  File "C:\Users\choyt\Downloads\msfs2020-google-map-2021-09-28\src\runner.py", line 15, in <module>
    my_hosts = Hosts()
  File "C:\Users\choyt\Downloads\msfs2020-google-map-2021-09-28\Python39\lib\site-packages\python_hosts\hosts.py", line 144, in __init__
    self.populate_entries()
  File "C:\Users\choyt\Downloads\msfs2020-google-map-2021-09-28\Python39\lib\site-packages\python_hosts\hosts.py", line 455, in populate_entries
    hosts_entries = [line for line in hosts_file]
  File "C:\Users\choyt\Downloads\msfs2020-google-map-2021-09-28\Python39\lib\site-packages\python_hosts\hosts.py", line 455, in <listcomp>
    hosts_entries = [line for line in hosts_file]
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence

C:\Users\choyt\Downloads\msfs2020-google-map-2021-09-28>pause
Press any key to continue . . .``

**Comment by derekhe** [comment]
能上传一下你的hosts文件么？
按理来说你把hosts文件删除了重新新建一个能够解决问题

**Comment by lacafjh** [comment]
类似的问题，但是我是本地新建的虚拟环境

```
conda create -n msfs2020-google-map python=3.9
conda activate msfs2020-google-map
conda install -c anaconda requests==2.25.1 requests[socks] retrying==1.3.3 diskcache==5.2.1 dnspython==2.1.0 pillow
pip install python-hosts==1.0.2
python src\app.py
```

填写好本地 Clash 的代理端口后点击主界面里的 run，终端内的输出如下

```
Restoring hosts
Restoring hosts
Exception in Tkinter callback
Traceback (most recent call last):
  File "\user\path\.conda\envs\msfs2020-google-map\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "\my\local\path\msfs2020-google-map\src\app.py", line 237, in run
    self.stop()
  File "\my\local\path\msfs2020-google-map\src\app.py", line 320, in stop
    restore_hosts()
  File "\my\local\path\msfs2020-google-map\src\runner.py", line 48, in restore_hosts
    hosts = Hosts()
  File "\user\path\.conda\envs\msfs2020-google-map\lib\site-packages\python_hosts\hosts.py", line 144, in __init__
    self.populate_entries()
  File "\user\path\.conda\envs\msfs2020-google-map\lib\site-packages\python_hosts\hosts.py", line 455, in populate_entries
    hosts_entries = [line for line in hosts_file]
  File "\user\path\.conda\envs\msfs2020-google-map\lib\site-packages\python_hosts\hosts.py", line 455, in <listcomp>
    hosts_entries = [line for line in hosts_file]
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence
Traceback (most recent call last):
  File "\my\local\path\msfs2020-google-map\src\app.py", line 375, in <module>
    root.mainloop()
  File "\user\path\.conda\envs\msfs2020-google-map\lib\tkinter\__init__.py", line 1429, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
Restoring hosts
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "\user\path\.conda\envs\msfs2020-google-map\lib\site-packages\python_hosts\hosts.py", line 455, in populate_entries
    hosts_entries = [line for line in hosts_file]
  File "\user\path\.conda\envs\msfs2020-google-map\lib\site-packages\python_hosts\hosts.py", line 455, in <listcomp>
    hosts_entries = [line for line in hosts_file]
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence
```

**Comment by lacafjh** [comment]
类似的问题，但是我是本地新建的虚拟环境

```
$ cd "\my\local\path\msfs2020-google-map"
$ conda create -n msfs2020-google-map python=3.9
$ conda activate msfs2020-google-map
$ conda install -c anaconda requests==2.25.1 requests[socks] retrying==1.3.3 diskcache==5.2.1 dnspython==2.1.0 pillow
$ pip install python-hosts==1.0.2
$ python src\app.py
```

填写好本地 Clash 的代理端口后点击主界面里的 run，终端内的输出如下

```
Restoring hosts
Restoring hosts
Exception in Tkinter callback
Traceback (most recent call last):
  File "\my\home\path\.conda\envs\msfs2020-google-map\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "\my\local\path\msfs2020-google-map\src\app.py", line 237, in run
    self.stop()
  File "\my\local\path\msfs2020-google-map\src\app.py", line 320, in stop
    restore_hosts()
  File "\my\local\path\msfs2020-google-map\src\runner.py", line 48, in restore_hosts
    hosts = Hosts()
  File "\my\home\path\.conda\envs\msfs2020-google-map\lib\site-packages\python_hosts\hosts.py", line 144, in __init__
    self.populate_entries()
  File "\my\home\path\.conda\envs\msfs2020-google-map\lib\site-packages\python_hosts\hosts.py", line 455, in populate_entries
    hosts_entries = [line for line in hosts_file]
  File "\my\home\path\.conda\envs\msfs2020-google-map\lib\site-packages\python_hosts\hosts.py", line 455, in <listcomp>
    hosts_entries = [line for line in hosts_file]
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence
Traceback (most recent call last):
  File "\my\local\path\msfs2020-google-map\src\app.py", line 375, in <module>
    root.mainloop()
  File "\my\home\path\.conda\envs\msfs2020-google-map\lib\tkinter\__init__.py", line 1429, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
Restoring hosts
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "\my\home\path\.conda\envs\msfs2020-google-map\lib\site-packages\python_hosts\hosts.py", line 455, in populate_entries
    hosts_entries = [line for line in hosts_file]
  File "\my\home\path\.conda\envs\msfs2020-google-map\lib\site-packages\python_hosts\hosts.py", line 455, in <listcomp>
    hosts_entries = [line for line in hosts_file]
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence
```

另外我 etc 目录里 host 只有几行其他服务用的内容，应该无关

```
# C:\WINDOWS\system32\drivers\etc\host
# UnblockNetEaseMusic（Go）
127.0.0.1 music.163.com
127.0.0.1 interface.music.163.com
# Added by Docker Desktop
192.168.1.180 host.docker.internal
192.168.1.180 gateway.docker.internal
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
```

**Comment by lacafjh** [comment]
类似的问题，但是我是本地新建的虚拟环境

```
$ cd "\my\local\path\msfs2020-google-map"
$ conda create -n msfs2020-google-map python=3.9
$ conda activate msfs2020-google-map
$ conda install -c anaconda requests==2.25.1 requests[socks] retrying==1.3.3 diskcache==5.2.1 dnspython==2.1.0 pillow
$ pip install python-hosts==1.0.2
$ python src\app.py
```

填写好本地 Clash 的代理端口后点击主界面里的 run，终端内的输出如下

```
Restoring hosts
Restoring hosts
Exception in Tkinter callback
Traceback (most recent call last):
  File "\my\home\path\.conda\envs\msfs2020-google-map\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "\my\local\path\msfs2020-google-map\src\app.py", line 237, in run
    self.stop()
  File "\my\local\path\msfs2020-google-map\src\app.py", line 320, in stop
    restore_hosts()
  File "\my\local\path\msfs2020-google-map\src\runner.py", line 48, in restore_hosts
    hosts = Hosts()
  File "\my\home\path\.conda\envs\msfs2020-google-map\lib\site-packages\python_hosts\hosts.py", line 144, in __init__
    self.populate_entries()
  File "\my\home\path\.conda\envs\msfs2020-google-map\lib\site-packages\python_hosts\hosts.py", line 455, in populate_entries
    hosts_entries = [line for line in hosts_file]
  File "\my\home\path\.conda\envs\msfs2020-google-map\lib\site-packages\python_hosts\hosts.py", line 455, in <listcomp>
    hosts_entries = [line for line in hosts_file]
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence
Traceback (most recent call last):
  File "\my\local\path\msfs2020-google-map\src\app.py", line 375, in <module>
    root.mainloop()
  File "\my\home\path\.conda\envs\msfs2020-google-map\lib\tkinter\__init__.py", line 1429, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
Restoring hosts
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "\my\home\path\.conda\envs\msfs2020-google-map\lib\site-packages\python_hosts\hosts.py", line 455, in populate_entries
    hosts_entries = [line for line in hosts_file]
  File "\my\home\path\.conda\envs\msfs2020-google-map\lib\site-packages\python_hosts\hosts.py", line 455, in <listcomp>
    hosts_entries = [line for line in hosts_file]
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence
```

另外我 etc 目录里 host 只有几行其他服务用的内容，应该无关

```
# C:\WINDOWS\system32\drivers\etc\host
# UnblockNetEaseMusic（Go）
127.0.0.1 music.163.com
127.0.0.1 interface.music.163.com
# Added by Docker Desktop
*** host.docker.internal
*** gateway.docker.internal
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
```

**Comment by derekhe** [comment]
这个可能是python_hosts这个不能正确的处理gbk字符集造成的。
我已经计划重新写一个处理hosts文件的东西了，这个库问题比较多。
