### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by JustGez** [derekhe/msfs2020-google-map#46]
Hi. Thanks for your hard work but it crashes on startup for me, the main popop doesn't load. Copy/paste of the output from the cmd window below.

C:\Games\Sim\MSFS Google Maps Mod>if exist .\Python39\python.exe (
echo "Use embedded python"
 .\Python39\python.exe src\app.py
)  else (
echo "Use user python"
 py -m pip install -r requirements.txt
 py src\app.py
)
"Use embedded python"
Traceback (most recent call last):
  File "C:\Games\Sim\MSFS Google Maps Mod\src\app.py", line 12, in <module>
    from runner import add_cert, override_hosts, restore_hosts, get_hosts_origin_ips
  File "C:\Games\Sim\MSFS Google Maps Mod\src\runner.py", line 9, in <module>
    __my_hosts = Hosts()
  File "C:\Games\Sim\MSFS Google Maps Mod\Python39\lib\site-packages\python_hosts\hosts.py", line 144, in __init__
    self.populate_entries()
  File "C:\Games\Sim\MSFS Google Maps Mod\Python39\lib\site-packages\python_hosts\hosts.py", line 457, in populate_entries
    entry_type = HostsEntry.get_entry_type(hosts_entry)
  File "C:\Games\Sim\MSFS Google Maps Mod\Python39\lib\site-packages\python_hosts\hosts.py", line 103, in get_entry_type
    if is_ipv6(entry_chunks[0]):
  File "C:\Games\Sim\MSFS Google Maps Mod\Python39\lib\site-packages\python_hosts\utils.py", line 32, in is_ipv6
    if socket.inet_pton(socket.AF_INET6, entry):
ValueError: embedded null character

C:\Games\Sim\MSFS Google Maps Mod>pause
Press any key to continue . . .

**Comment by derekhe** [comment]
Please try delete C:\windows\system32\drivers\etc\hosts file. Please backup this file first.
