### ISSUE TITLE
[BUG] UnableToWriteHosts() python_hosts.exception.UnableToWriteHosts

### ISSUE THREAD

**Issue by JosephRDawson** [derekhe/msfs2020-google-map#60]
**Describe the bug**
I do run it as Administrator using Windows 11 Pro but it is not able to modify my host file for some reason.

**To Reproduce**
Run batch file as administrator no errors.
Then start run and I get an error that it can't modify the host file.
I can modify the host file with notepad without issues.
I have a standard host file with no special information within it.

**Expected behavior**

**Screenshots**
Traceback (most recent call last):
  File "C:\Users\Joe\Desktop\msfs2020-google-map-2021-11-11\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\Joe\Desktop\msfs2020-google-map-2021-11-11\src\app.py", line 234, in run
    self.stop()
  File "C:\Users\Joe\Desktop\msfs2020-google-map-2021-11-11\src\app.py", line 301, in stop
    restore_hosts()
  File "C:\Users\Joe\Desktop\msfs2020-google-map-2021-11-11\src\runner.py", line 42, in restore_hosts
    hosts.write()
  File "C:\Users\Joe\Desktop\msfs2020-google-map-2021-11-11\Python39\lib\site-packages\python_hosts\hosts.py", line 216, in write
    raise UnableToWriteHosts()
python_hosts.exception.UnableToWriteHosts

**Desktop (please complete the following information):**
 - OS:  Windows 11 Pro
 - MOD Using the 11-11 relases
 - MSFS MS flightsim ultimate version from ms store.
 - 
**Additional context**
No additional information.

**Comment by JosephRDawson** [comment]
MY AV was the issue!
