### ISSUE TITLE
Program won't run

### ISSUE THREAD

**Issue by bashernz** [derekhe/msfs2020-google-map#62]
I get the Following when i click run 

Restoring hosts
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\fs2020\msfs2020-google-map-2021-11-10\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "D:\fs2020\msfs2020-google-map-2021-11-10\src\app.py", line 230, in run
    self.stop()
  File "D:\fs2020\msfs2020-google-map-2021-11-10\src\app.py", line 295, in stop
    restore_hosts()
  File "D:\fs2020\msfs2020-google-map-2021-11-10\src\runner.py", line 40, in restore_hosts
    hosts = Hosts()
  File "D:\fs2020\msfs2020-google-map-2021-11-10\Python39\lib\site-packages\python_hosts\hosts.py", line 144, in __init__
    self.populate_entries()
  File "D:\fs2020\msfs2020-google-map-2021-11-10\Python39\lib\site-packages\python_hosts\hosts.py", line 457, in populate_entries
    entry_type = HostsEntry.get_entry_type(hosts_entry)
  File "D:\fs2020\msfs2020-google-map-2021-11-10\Python39\lib\site-packages\python_hosts\hosts.py", line 103, in get_entry_type
    if is_ipv6(entry_chunks[0]):
  File "D:\fs2020\msfs2020-google-map-2021-11-10\Python39\lib\site-packages\python_hosts\utils.py", line 32, in is_ipv6
    if socket.inet_pton(socket.AF_INET6, entry):
ValueError: embedded null character

windows 10  MS store version of MSFS

**Comment by bashernz** [comment]
Saw similar issue in closed issues. and renamed my host file . it now works
