### ISSUE TITLE
证书验证失败

### ISSUE THREAD

**Issue by sihua746** [derekhe/msfs2020-google-map#7]
证书验证失败，换了地区也是一样，上一个版本没问题，打开证书显示Windows没有足够信息，不能验证该证书

**Comment by derekhe** [comment]
这个问题我还没搞明白怎么回事，我也遇到过。启动时候直接点击信任就好了。

**Comment by sihua746** [comment]
Traceback (most recent call last):
  File "flask\app.py", line 2070, in wsgi_app
  File "flask\app.py", line 1515, in full_dispatch_request
  File "flask\app.py", line 1513, in full_dispatch_request
  File "flask\app.py", line 1499, in dispatch_request
  File "server.py", line 89, in tiles
  File "requests\api.py", line 76, in get
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='kh.ssl.ak.tiles.virtualearth.net', port=443): Max retries exceeded with url: /tiles/gen (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
127.0.0.1 - - [19/Aug/2021 22:17:35] "GET /tiles/gen HTTP/1.1" 500 -
这个是刚才开游戏显示的

**Comment by derekhe** [comment]
你试试管理员权限打开

**Comment by sihua746** [comment]
好的，我试试，谢谢

**Comment by JimFanyi** [comment]
certs文件夹中的证书在windows中显示没有足够信息，不能验证该证书

**Comment by derekhe** [comment]
@JimFanyi 是的，这个证书是自签名的证书，windows验证不会通过的。脚本会自动把它加到windows的受信任的根证书来绕过验证。

**Comment by derekhe** [comment]
如果游戏提示证书问题，请直接同意即可。
