### ISSUE TITLE
Errors during start

### ISSUE THREAD

**Issue by hoplaHL** [derekhe/msfs2020-google-map#98]
Hi,

i got this error when starting the program as admin ...

Traceback (most recent call last):
  File "C:\Users\xxx\Downloads\msfs2020-google-map-2021-11-18_Iwuxg\src\app.py", line 252, in run
    output = self.config_dns(output)
  File "C:\Users\xxx\Downloads\msfs2020-google-map-2021-11-18_Iwuxg\src\app.py", line 225, in config_dns
    for k, v in get_hosts_origin_ips().items():
  File "C:\Users\xxx\Downloads\msfs2020-google-map-2021-11-18_Iwuxg\src\runner.py", line 28, in get_hosts_origin_ips
    dns_resolver = dns.resolver.Resolver()
  File "C:\Users\xxx\Downloads\msfs2020-google-map-2021-11-18_Iwuxg\Python39\lib\site-packages\dns\resolver.py", line 732, in __init__
    self.read_registry()
  File "C:\Users\xxxx\Downloads\msfs2020-google-map-2021-11-18_Iwuxg\Python39\lib\site-packages\dns\resolver.py", line 928, in read_registry
    self._config_win32_fromkey(key, False)
  File "C:\Users\xxxx\Downloads\msfs2020-google-map-2021-11-18_Iwuxg\Python39\lib\site-packages\dns\resolver.py", line 891, in _config_win32_fromkey
    self._config_win32_domain(dom)
  File "C:\Users\xxxx\Downloads\msfs2020-google-map-2021-11-18_Iwuxg\Python39\lib\site-packages\dns\resolver.py", line 854, in _config_win32_domain
    self.domain = dns.name.from_text(str(domain))
  File "C:\Users\xxxx\Downloads\msfs2020-google-map-2021-11-18_Iwuxg\Python39\lib\site-packages\dns\name.py", line 942, in from_text
    raise EmptyLabel
dns.name.EmptyLabel: A DNS label is empty.

What's the problem??

**Comment by derekhe** [comment]
I will try to fix it.

**Comment by derekhe** [comment]
Please try this version: https://github.com/derekhe/msfs2020-google-map/releases/tag/2.3.0

**Comment by hoplaHL** [comment]
Perfect job! ... it works!  Thanks for this quick response!!

**Comment by derekhe** [comment]
Good, I will close this.
